### ISSUE TITLE
scala-2.12/windows known problems?

### ISSUE THREAD

**Issue by r2evans** [dselivanov/rscalaKafka#2]
I'm having a hard time getting connections to work on my windows install of R:

I'm running kafka on a remote VM. When I use `rscalaKafka` on the local R instance (ubuntu 16.04, R-3.3.3, scala-2.11.6-6), I can produce and consume messages without error. On windows over a SSH, the console batch scripts work (with expected/correct output, omitted):

```bat
kafka-topics.bat --list --zookeeper localhost:2181
kafka-console-producer.bat --broker-list localhost:9092 --topic test
kafka-console-consumer.bat --bootstrap-server localhost:9092 --topic test --from-beginning
```

from this I believe the forwarding pipes are working. From R, I test scala:

```r
packageVersion("rscala")
# [1] '1.0.15'
packageVersion("rscalaKafka")
# [1] '0.1.0'
str(rscala::scalaInfo())
# List of 4
#  $ cmd          : chr "C:\\Users\\r2\\.rscala\\scala-2.12.1\\bin\\scala"
#  $ home         : chr "C:/Users/r2/.rscala/scala-2.12.1"
#  $ version      : chr "2.11.8"
#  $ major.version: chr "2.11"
rscala:::`%~%`(rscalaKafka:::s, "3+8")
# [1] 11
system("java -version")
# java version "1.8.0_121"
# Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
# Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

I think this means the Scala and Java installs are at least partially functional. I'm running Win10, R-3.3.3, Oracle Java 8 (1.8). I tried first with Scala-2.12.1 and got a similar error as below. I downgraded to 2.11.8; and even though the messages say ">= 2.11", it doesn't find 2.11. Setting `SCALA_HOME` (env var) before hand seemed to preclude this problem.

Anyway, the problem:

```r
producer <- KafkaProducer$new(topic_name = "test", broker_list = "127.0.0.1:9092", config = list())
# log4j:WARN No appenders could be found for logger (org.apache.kafka.clients.producer.ProducerConfig).
# log4j:WARN Please initialize the log4j system properly.
# log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
# java.lang.reflect.InvocationTargetException
# 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
# 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
# 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
# 	at java.lang.reflect.Method.invoke(Unknown Source)
# 	at org.ddahl.rscala.ScalaServer.callFunction(ScalaServer.scala:77)
# 	at org.ddahl.rscala.ScalaServer.doInvoke(ScalaServer.scala:196)
# 	at org.ddahl.rscala.ScalaServer.org$ddahl$rscala$ScalaServer$$heart(ScalaServer.scala:572)
# 	at org.ddahl.rscala.ScalaServer.run(ScalaServer.scala:599)
# 	at org.ddahl.rscala.Main$.delayedEndpoint$org$ddahl$rscala$Main$1(Main.scala:5)
# 	at org.ddahl.rscala.Main$delayedInit$body.apply(Main.scala:3)
# 	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
# 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
# 	at scala.App$$anonfun$main$1.apply(App.scala:76)
# 	at scala.App$$anonfun$main$1.apply(App.scala:76)
# 	at scala.collection.immutable.List.foreach(List.scala:381)
# 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
# 	at scala.App$class.main(App.scala:76)
# 	at org.ddahl.rscala.Main$.main(Main.scala:3)
# 	at org.ddahl.rscala.Main.main(Main.scala)
# 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
# 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
# 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
# 	at java.lang.reflect.Method.invoke(Unknown Source)
# 	at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
# 	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
# 	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
# 	at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
# 	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
# 	at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
# 	at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
# 	at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
# 	at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
# 	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:65)
# 	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
# 	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
# 	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
# 	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
# Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
# 	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:342)
# 	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:191)
# 	at org.dselivanov.rkafka.RscalaKafkaProducer.<init>(RscalaKafkaProducer.scala:36)
# 	at $line5.$read$$iw$$iw$$anonfun$1.apply(<console>:12)
# 	at $line5.$read$$iw$$iw$$anonfun$1.apply(<console>:12)
# 	... 37 more
# Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.serialization.StringSerializer is not an instance of org.apache.kafka.common.serialization.Serializer
# 	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:205)
# 	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:231)
# 	... 41 more
# java.lang.reflect.InvocationTargetException
# org.apache.kafka.common.KafkaException: Failed to construct kafka producer
# Error in f(..., as.reference = as.reference, gc = gc) (from <text>#31) : Invocation error.
```

Thoughts?

**Comment by dselivanov** [comment]
This looks strange:
>List of 4
$ cmd          : chr "C:\\Users\\r2\\.rscala\\**scala-2.12.1**\\bin\\scala"
$ home         : chr "C:/Users/r2/.rscala/**scala-2.12.1**"
$ version      : chr "**2.11.8**"
$ major.version: chr "**2.11**"

To be honest I don't know what is happening. Just guessing that such strange exceptions may be related that `rscala` uses `scala 2.12` while client is built with 2.11.

**Comment by r2evans** [comment]
That's because I tried a few things to work around the fact that rscala wouldn't see version 2.11.8 without assistance. My first workaround (which generated this output) was to simply rename the directory from 2.11.8 to 2.12.1, and later troubleshooting steps convinced me to better read the error message and set SCALA_HOME before loading the package (which also worked). The error persisted with no change in behavior.

Do you have any suggestions for better troubleshooting? I don't think it is the Scala version that is causing the problem here.


On Mar 25, 2017 00:02, Dmitriy Selivanov <notifications@github.com> wrote:This looks strange:

List of 4
$ cmd          : chr "C:\Users\r2\.rscala\scala-2.12.1\bin\scala"
$ home         : chr "C:/Users/r2/.rscala/scala-2.12.1"
$ version      : chr "2.11.8"
$ major.version: chr "2.11"

To be honest I don't know what is happening. Just guessing that such strange exceptions may be related that rscala uses scala 2.12 while client is built with 2.11.

**Comment by dselivanov** [comment]
I will try on my windows machine

**Comment by r2evans** [comment]
For the record, I reinstalled scala-2.12.1 (problem still present), and here's the info:

```r
str(rscala::scalaInfo())
# List of 4
#  $ cmd          : chr "C:\\Users\\r2\\.rscala\\scala-2.12.1\\bin\\scala"
#  $ home         : chr "C:/Users/r2/.rscala/scala-2.12.1"
#  $ version      : chr "2.12.1"
#  $ major.version: chr "2.12"
```

Sorry for the confusion.

**Comment by dselivanov** [comment]
I have other strange error:
```r
library(rscalaKafka)
producer = KafkaProducer$new(topic_name = "test", 
                             broker_list = "localhost:9092", config = list())
```
> Error in f(..., as.reference = as.reference, gc = gc) : Invocation error. 
5.stop("Invocation error.") at <text>#31
4.f(..., as.reference = as.reference, gc = gc) 
3.s$do("org.dselivanov.rkafka.RscalaKafkaProducer")$new(topic_name, 
    broker_list, config_keys, config_values) at producer.R#47
2..subset2(public_bind_env, "initialize")(...) 
1.KafkaProducer$new(topic_name = "test", broker_list = "localhost:9092", 
    config = list())

**Comment by dselivanov** [comment]
@dbdahl sorry for disturbing. We got stock here. How to debug such things?
**EDIT** our apologies for disturbing you. Seems this is a windows network/firewall issue.

**Comment by r2evans** [comment]
My apologies, the issue may be broader ... I'm trying [`rkafka`](https://cran.r-project.org/web/packages/rkafka/index.html) in a known-working configuration, and it works from ubuntu and not from windows. It's not a java-version thing (both running 1.8.0), and I don't think it's a network thing (windows is on the LAN, ubuntu is on the same host).

Windows `kafka-topics.bat` is able to list the topics, so port 2181 is working. Perhaps it's just kafka on 9092 that is mis-reporting its advertised listener or something like that.

Sorry to cause you work, not certain how to proceed or troubleshoot. I'll report back if I find something actionable.

**Comment by dselivanov** [comment]
@r2evans thanks for investigation. Couldn't it be something related to windows firewall?

**Comment by r2evans** [comment]
Yes, I thought of that. Though my sense of control over McAfee's vague interface is not 100% certain, I believe I've disabled both it and the Windows Firewall itself, still no luck. The fact that port 2181 succeeds while 9092 fails is very interesting to me. I'm not a java/scala guru, is it likely that Oracle Java 8 for Windows has issues that neither Windows Java 7 nor Linux Java 8 has?

**Comment by dselivanov** [comment]
I'm​ not Java expert as well :-( working today on Windows was also tough :)) forgot how it can be.
